#!/bin/bash
set -e

echo "Building Frontend image..."
docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$COMMIT_SHA ./wpoms_web

DATE_TAG=$(date +%Y-%m-%d)-$COMMIT_SHA
VERSION_TAG=$VERSION_PREFIX.$BUILD_NUMBER

echo "Tagging Frontend images..."
docker tag $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$COMMIT_SHA $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$DATE_TAG
docker tag $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$COMMIT_SHA $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$VERSION_TAG

echo "Pushing Frontend images..."
docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$DATE_TAG
docker push $ECR_REGISTRY/$ECR_REPOSITORY_FRONTEND:$VERSION_TAG

echo "Building Backend image..."
docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$COMMIT_SHA ./wpoms_admin

echo "Tagging Backend images..."
docker tag $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$COMMIT_SHA $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$DATE_TAG
docker tag $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$COMMIT_SHA $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$VERSION_TAG

echo "Pushing Backend images..."
docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$DATE_TAG
docker push $ECR_REGISTRY/$ECR_REPOSITORY_BACKEND:$VERSION_TAG

echo "Build and push complete!"